import exampleImage from "../../../../assets/images/admin/example.png";
export const NoticeModul = [
    {
        id: "1",
        heading: "Notice",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
    },
    {
        id: "2",
        heading: "Event",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
    },
    {
        id: "3",
        heading: "Announce",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
    },
    {
        id: "4",
        heading: "Event",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
    },
    {
        id: "5",
        heading: "Notice",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
    },
    {
        id: "6",
        heading: "Notice",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
    },
    {
        id: "7",
        heading: "Event",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
    },
    {
        id: "8",
        heading: "Announce",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
    },
    {
        id: "9",
        heading: "Event",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
    },
    {
        id: "10",
        heading: "Notice",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
    },
    {
        id: "11",
        heading: "Notice",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
    },
    {
        id: "12",
        heading: "Event",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
    },
    {
        id: "13",
        heading: "Announce",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
    },
    {
        id: "14",
        heading: "Event",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
    },
    {
        id: "15",
        heading: "Notice",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
    },
];
export const PromotionModul = [
    {
        id: "1",
        heading: "Promotion",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
        image: "",
        url: "example.com",
    },
    {
        id: "2",
        heading: "Promotion",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
        image: "",
        url: "example.com",
    },
    {
        id: "3",
        heading: "Promotion",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
        image: "",
        url: "example.com",
    },
    {
        id: "4",
        heading: "Promotion",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
        image: "",
        url: "example.com",
    },
    {
        id: "5",
        heading: "Promotion",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
        image: "",
        url: "example.com",
    },
    {
        id: "6",
        heading: "Promotion",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
        image: "",
        url: "example.com",
    },
    {
        id: "7",
        heading: "Promotion",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
        image: "",
        url: "example.com",
    },
    {
        id: "8",
        heading: "Promotion",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
        image: "",
        url: "example.com",
    },
    {
        id: "9",
        heading: "Promotion",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
        image: "",
        url: "example.com",
    },
    {
        id: "10",
        heading: "Promotion",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
        image: "",
        url: "example.com",
    },
    {
        id: "11",
        heading: "Promotion",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
        image: "",
        url: "example.com",
    },
    {
        id: "12",
        heading: "Promotion",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
        image: "",
        url: "example.com",
    },
    {
        id: "13",
        heading: "Promotion",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
        image: "",
        url: "example.com",
    },
    {
        id: "14",
        heading: "Promotion",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
        image: "",
        url: "example.com",
    },
    {
        id: "15",
        heading: "Promotion",
        title: "Join the event!",
        desc: "GM. Text crow pig sell mars nft cartoon netflix  Thank you.",
        date: "2022.11.23",
        image: "",
        url: "example.com",
    },
];
export const CategoryModul = [
    {
        id: "1",
        keyword: "Art",
        image: exampleImage,
    },
    {
        id: "2",
        keyword: "Game",
        image: exampleImage,
    },
    {
        id: "3",
        keyword: "Music",
        image: exampleImage,
    },
    {
        id: "4",
        keyword: "Photography",
        image: exampleImage,
    },
    {
        id: "5",
        keyword: "Video",
        image: exampleImage,
    },
];
export const CollectionModul = [
    {
        id: "1",
        title: "Louis Vuitton",
        enabled: "1",
        symbol: "C4C",
        tokenType: "ERC-721",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "23",
    },
    {
        id: "2",
        title: "Johnson & Johnson",
        enabled: "0",
        symbol: "ABC",
        tokenType: "ERC-1155",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "10,000",
    },
    {
        id: "3",
        title: "Starbucks",
        enabled: "0",
        symbol: "KAY",
        tokenType: "SPL",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "500",
    },
    {
        id: "4",
        title: "The Walt Disney ",
        enabled: "0",
        symbol: "UFO",
        tokenType: "SPL",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "2",
    },
    {
        id: "5",
        title: "Mitsubishi",
        enabled: "1",
        symbol: "DSG",
        tokenType: "KIP-17",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "13",
    },
    {
        id: "6",
        title: "IBM",
        enabled: "0",
        symbol: "MSG",
        tokenType: "KIP-37",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "4,000",
    },
    {
        id: "7",
        title: "Louis Vuitton",
        enabled: "1",
        symbol: "C4C",
        tokenType: "ERC-721",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "23",
    },
    {
        id: "8",
        title: "Johnson & Johnson",
        enabled: "0",
        symbol: "ABC",
        tokenType: "ERC-1155",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "10,000",
    },
    {
        id: "9",
        title: "Starbucks",
        enabled: "0",
        symbol: "KAY",
        tokenType: "SPL",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "500",
    },
    {
        id: "10",
        title: "The Walt Disney ",
        enabled: "0",
        symbol: "UFO",
        tokenType: "SPL",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "2",
    },
    {
        id: "11",
        title: "Mitsubishi",
        enabled: "1",
        symbol: "DSG",
        tokenType: "KIP-17",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "13",
    },
    {
        id: "12",
        title: "IBM",
        enabled: "0",
        symbol: "MSG",
        tokenType: "KIP-37",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "4,000",
    },
    {
        id: "13",
        title: "Louis Vuitton",
        enabled: "1",
        symbol: "C4C",
        tokenType: "ERC-721",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "23",
    },
    {
        id: "14",
        title: "Johnson & Johnson",
        enabled: "0",
        symbol: "ABC",
        tokenType: "ERC-1155",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "10,000",
    },
    {
        id: "15",
        title: "Starbucks",
        enabled: "0",
        symbol: "KAY",
        tokenType: "SPL",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "500",
    },
    {
        id: "16",
        title: "The Walt Disney ",
        enabled: "0",
        symbol: "UFO",
        tokenType: "SPL",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "2",
    },
    {
        id: "17",
        title: "Mitsubishi",
        enabled: "1",
        symbol: "DSG",
        tokenType: "KIP-17",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "13",
    },
    {
        id: "18",
        title: "IBM",
        enabled: "0",
        symbol: "MSG",
        tokenType: "KIP-37",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "4,000",
    },
    {
        id: "19",
        title: "Louis Vuitton",
        enabled: "1",
        symbol: "C4C",
        tokenType: "ERC-721",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "23",
    },
    {
        id: "20",
        title: "Johnson & Johnson",
        enabled: "0",
        symbol: "ABC",
        tokenType: "ERC-1155",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "10,000",
    },
    {
        id: "21",
        title: "Starbucks",
        enabled: "0",
        symbol: "KAY",
        tokenType: "SPL",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "500",
    },
    {
        id: "22",
        title: "The Walt Disney ",
        enabled: "0",
        symbol: "UFO",
        tokenType: "SPL",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "2",
    },
    {
        id: "23",
        title: "Mitsubishi",
        enabled: "1",
        symbol: "DSG",
        tokenType: "KIP-17",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "13",
    },
    {
        id: "24",
        title: "IBM",
        enabled: "0",
        symbol: "MSG",
        tokenType: "KIP-37",
        address: "0xd4AEkfkc3410xd4AEkfkc341",
        totalSupply: "4,000",
    },
];
export const FaqAdmModul = [
    {
        id: "1",
        quest: "How does it work",
        category: "General",
        answer:
            'The Stacks series of products: Stacks: Landing Page Kit, Stacks: Portfolio Kit,  Stacks: eCommerce Kit. "Stacks is a production-ready library of stackable content blocks built in React Native. Mix-and-match dozens of responsive elements to quickly configure your favorite landing page layouts or hit the ground running with 10 pre-built templates, all in light or dark mode." ',
    },
    {
        id: "2",
        quest: "How to start with Stacks",
        category: "General",
        answer:
            'The Stacks series of products: Stacks: Landing Page Kit, Stacks: Portfolio Kit,  Stacks: eCommerce Kit. "Stacks is a production-ready library of stackable content blocks built in React Native. Mix-and-match dozens of responsive elements to quickly configure your favorite landing page layouts or hit the ground running with 10 pre-built templates, all in light or dark mode." ',
    },
    {
        id: "3",
        quest: "Dose it suppport Dark Mode",
        category: "Support",
        answer:
            'The Stacks series of products: Stacks: Landing Page Kit, Stacks: Portfolio Kit,  Stacks: eCommerce Kit. "Stacks is a production-ready library of stackable content blocks built in React Native. Mix-and-match dozens of responsive elements to quickly configure your favorite landing page layouts or hit the ground running with 10 pre-built templates, all in light or dark mode." ',
    },
    {
        id: "4",
        quest: "Does it support Auto-Layout",
        category: "Support",
        answer:
            'The Stacks series of products: Stacks: Landing Page Kit, Stacks: Portfolio Kit,  Stacks: eCommerce Kit. "Stacks is a production-ready library of stackable content blocks built in React Native. Mix-and-match dozens of responsive elements to quickly configure your favorite landing page layouts or hit the ground running with 10 pre-built templates, all in light or dark mode." ',
    },
    {
        id: "5",
        quest: "What is Stacks Design System",
        category: "Creator",
        answer:
            'The Stacks series of products: Stacks: Landing Page Kit, Stacks: Portfolio Kit,  Stacks: eCommerce Kit. "Stacks is a production-ready library of stackable content blocks built in React Native. Mix-and-match dozens of responsive elements to quickly configure your favorite landing page layouts or hit the ground running with 10 pre-built templates, all in light or dark mode." ',
    },
];
export const UserAdmModul = [
    {
        id: "1",
        userName: "David Kim",
        address:"0x123u129038901283091283901283",
        status: "Creator",
        email: "code4chain@naver.com",
        joinDate: "22-10-10 13:24:45",
        marketing: "Agree",
    },
    {
        id: "2",
        userName: "Jackson",
        address: "0x123u129038901283091283901283",
        status: "User",
        email: "code4chain@naver.com",
        joinDate: "22-10-10 13:24:45",
        marketing: "Disagree",
    },
    {
        id: "3",
        userName: "Sam",
        address: "0x123u129038901283091283901283",
        status: "User",
        email: "code4chain@naver.com",
        joinDate: "22-10-10 13:24:45",
        marketing: "Agree",
    },
    {
        id: "4",
        userName: "Aiden",
        address: "0x123u129038901283091283901283",
        status: "User",
        email: "code4chain@naver.com",
        joinDate: "22-10-10 13:24:45",
        marketing: "Disagree",
    },
    {
        id: "5",
        userName: "C4C",
        status: "Creator",
        email: "code4chain@naver.com",
        joinDate: "22-10-10 13:24:45",
        marketing: "Agree",
    },
    {
        id: "6",
        userName: "ABCDEFG",
        status: "User",
        email: "code4chain@naver.com",
        joinDate: "22-10-10 13:24:45",
        marketing: "Disagree",
    },
    {
        id: "7",
        userName: "David Kim",
        status: "Creator",
        email: "code4chain@naver.com",
        joinDate: "22-10-10 13:24:45",
        marketing: "Disagree",
    },
    {
        id: "8",
        userName: "Jackson",
        status: "User",
        email: "code4chain@naver.com",
        joinDate: "22-10-10 13:24:45",
        marketing: "Disagree",
    },
    {
        id: "9",
        userName: "Sam",
        status: "User",
        email: "code4chain@naver.com",
        joinDate: "22-10-10 13:24:45",
        marketing: "Agree",
    },
    {
        id: "10",
        userName: "Aiden",
        status: "User",
        email: "code4chain@naver.com",
        joinDate: "22-10-10 13:24:45",
        marketing: "Disagree",
    },
    {
        id: "11",
        userName: "C4C",
        status: "Creator",
        email: "code4chain@naver.com",
        joinDate: "22-10-10 13:24:45",
        marketing: "Disagree",
    },
    {
        id: "12",
        userName: "ABCDEFG",
        status: "User",
        email: "code4chain@naver.com",
        joinDate: "22-10-10 13:24:45",
        marketing: "Disagree",
    },
    {
        id: "13",
        userName: "David Kim",
        status: "Creator",
        email: "code4chain@naver.com",
        joinDate: "22-10-10 13:24:45",
        marketing: "Agree",
    },
    {
        id: "14",
        userName: "Jackson",
        status: "User",
        email: "code4chain@naver.com",
        joinDate: "22-10-10 13:24:45",
        marketing: "Disagree",
    },
    {
        id: "15",
        userName: "Sam",
        status: "User",
        email: "code4chain@naver.com",
        joinDate: "22-10-10 13:24:45",
        marketing: "Agree",
    },
    {
        id: "16",
        userName: "Aiden",
        status: "User",
        email: "code4chain@naver.com",
        joinDate: "22-10-10 13:24:45",
        marketing: "Disagree",
    },
    {
        id: "17",
        userName: "C4C",
        status: "Creator",
        email: "code4chain@naver.com",
        joinDate: "22-10-10 13:24:45",
        marketing: "Disagree",
    },
    {
        id: "18",
        userName: "ABCDEFG",
        status: "User",
        email: "code4chain@naver.com",
        joinDate: "22-10-10 13:24:45",
        marketing: "Disagree",
    },
];
